<a href="https://colab.research.google.com/github/BNavya1995/car_data_set/blob/main/Car_Data__set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("/content/used_cars_messy.csv")
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  object
 2   brand              15661 non-null  object
 3   model              15661 non-null  object
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  object
 6   seller_type        15661 non-null  object
 7   fuel_type          15661 non-null  object
 8   transmission_type  15661 non-null  object
 9   mileage            14376 non-null  object
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.7+ MB

In [3]:
df.shape

(15661, 14)

In [4]:
df.describe()

,Unnamed: 0,vehicle_age,engine,max_power,seats,selling_price
count,15661.000000,15661.000000,13792.000000,14862.000000,15218.000000,1.550300e+04
mean,9808.189643,6.036843,1480.489342,100.513582,5.324418,1.032764e+06
std,5642.981540,3.015072,511.446057,42.854632,0.805993,1.607380e+07
min,0.000000,0.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4901.000000,4.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9858.000000,6.000000,1248.000000,88.500000,5.000000,5.550000e+05
75%,14666.000000,8.000000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,6592.000000,626.000000,9.000000,1.000000e+09

In [5]:
df.isnull().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(169)

In [7]:
df[df.duplicated(keep=False)].sort_values('brand').head(30)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
9347,1210,Audi A4,Audi,A4,9,23994,Dealer,Diesel,Automatic,17.11,NaN,174.33,5.0,1275000.0
5920,1210,Audi A4,Audi,A4,9,23994,Dealer,Diesel,Automatic,17.11,NaN,174.33,5.0,1275000.0
13398,6871,Audi A4,Audi,A4,4,53700,Individual,Diesel,Automatic,18.25,1968.0,187.74,5.0,1760000.0
3642,6871,Audi A4,Audi,A4,4,53700,Individual,Diesel,Automatic,18.25,1968.0,187.74,5.0,1760000.0
3709,11969,BMW X5,BMW,X5,7,68000,Dealer,Diesel,Automatic,11.7,2993.0,245.00,5.0,3200000.0
8441,16053,BMW 6,BMW,6,3,11000,Dealer,Diesel,Automatic,17.09,2993.0,NaN,4.0,5600000.0
4958,11969,BMW X5,BMW,X5,7,68000,Dealer,Diesel,Automatic,11.7,2993.0,245.00,5.0,3200000.0
867,16053,BMW 6,BMW,6,3,11000,Dealer,Diesel,Automatic,17.09,2993.0,NaN,4.0,5600000.0
11616,7216,Datsun GO,Datsun,GO,4,23142,Dealer,Petrol,Manual,NaN,1198.0,67.00,5.0,360000.0
4973,7216,Datsun GO,Datsun,GO,4,23142,Dealer,Petrol,Manual,NaN,1198.0,67.00,5.0,360000.0
2688,655,Ford Ecosport,Ford,Ecosport,4,35000,Individual,Diesel,Manual,23.0,1498.0,98.96,5.0,785000.0
2646,16964,Ford Ecosport,Ford,Ecosport,4,40000,Individual,Diesel,Manual,23.0,1498.0,98.96,5.0,885000.0
10901,655,Ford Ecosport,Ford,Ecosport,4,35000,Individual,Diesel,Manual,23.0,1498.0,98.96,5.0,785000.0
2212,5242,Ford Figo,Ford,Figo,5,25780,Dealer,Petrol,Manual,18.16,1196.0,NaN,5.0,525000.0
15102,16964,Ford Ecosport,Ford,Ecosport,4,40000,Individual,Diesel,Manual,23.0,1498.0,98.96,5.0,885000.0
8826,5242,Ford Figo,Ford,Figo,5,25780,Dealer,Petrol,Manual,18.16,1196.0,NaN,5.0,525000.0
8618,10117,Ford Ecosport,Ford,Ecosport,3,25358,Dealer,Diesel,Manual,21.7,1498.0,98.96,5.0,950000.0
9177,8236,Ford Ecosport,Ford,Ecosport,2,42000,Dealer,Diesel,Manual,23.0,1498.0,98.96,5.0,1021000.0
3085,8236,Ford Ecosport,Ford,Ecosport,2,42000,Dealer,Diesel,Manual,23.0,1498.0,98.96,5.0,1021000.0
10804,5776,Ford Figo,Ford,Figo,11,93000,Dealer,Diesel,Manual,20.0,1399.0,68.00,5.0,265000.0
8785,10117,Ford Ecosport,Ford,Ecosport,3,25358,Dealer,Diesel,Manual,21.7,1498.0,98.96,5.0,950000.0
14340,9470,Ford Figo,Ford,Figo,9,90000,Individual,Diesel,Manual,20.0,1399.0,68.00,5.0,150000.0
441,9470,Ford Figo,Ford,Figo,9,90000,Individual,Diesel,Manual,20.0,1399.0,68.00,5.0,150000.0
13387,5295,Ford Ecosport,Ford,Ecosport,3,50000,Individual,Diesel,Manual,23.0,1498.0,98.96,5.0,980000.0
15297,5776,Ford Figo,Ford,Figo,11,93000,Dealer,Diesel,Manual,20.0,1399.0,68.00,5.0,265000.0
4855,5295,Ford Ecosport,Ford,Ecosport,3,50000,Individual,Diesel,Manual,23.0,1498.0,98.96,5.0,980000.0
3732,14192,Honda Amaze,Honda,Amaze,3,17000,Dealer,Petrol,Automatic,18.3,1199.0,88.76,5.0,600000.0
5938,14214,Honda City,Honda,City,6,60000,Dealer,Diesel,Manual,26.0,1498.0,98.60,5.0,595000.0
5735,13242,Honda Jazz,Honda,Jazz,4,525000,Dealer,Petrol,Manual,18.7,1199.0,88.70,5.0,525000.0
2373,2381,Honda City,Honda,City,12,120000,Individual,Petrol,Manual,17.0,1497.0,118.00,5.0,235000.0

In [8]:
cat_columns=['car_name','brand','seller_type','fuel_type','transmission_type']

for col in cat_columns:
  unique_value=df[col].unique()
  print(f"\n {col} in {len(unique_value)} unique values):")
  print(sorted(unique_value))

 car_name in 121 unique values):
['Audi A4', 'Audi A6', 'Audi A8', 'Audi Q7', 'BMW 3', 'BMW 5', 'BMW 6', 'BMW 7', 'BMW X1', 'BMW X3', 'BMW X4', 'BMW X5', 'BMW Z4', 'Bentley Continental', 'Datsun GO', 'Datsun RediGO', 'Datsun redi-GO', 'Ferrari GTC4Lusso', 'Force Gurkha', 'Ford Aspire', 'Ford Ecosport', 'Ford Endeavour', 'Ford Figo', 'Ford Freestyle', 'Honda Amaze', 'Honda CR', 'Honda CR-V', 'Honda City', 'Honda Civic', 'Honda Jazz', 'Honda WR-V', 'Hyundai Aura', 'Hyundai Creta', 'Hyundai Elantra', 'Hyundai Grand', 'Hyundai Santro', 'Hyundai Tucson', 'Hyundai Venue', 'Hyundai Verna', 'Hyundai i10', 'Hyundai i20', 'ISUZU MUX', 'Isuzu D-Max', 'Isuzu MUX', 'Jaguar F-PACE', 'Jaguar XE', 'Jaguar XF', 'Jeep Compass', 'Jeep Wrangler', 'Kia Carnival', 'Kia Seltos', 'Land Rover Rover', 'Lexus ES', 'Lexus NX', 'Lexus RX', 'MG Hector', 'Mahindra Alturas', 'Mahindra Bolero', 'Mahindra KUV', 'Mahindra KUV100', 'Mahindra Marazzo', 'Mahindra Scorpio', 'Mahindra Thar', 'Mahindra XUV300', 'Mahindra XUV500', 'Maruti Alto', 'Maruti Baleno', 'Maruti Celerio', 'Maruti Ciaz', 'Maruti Dzire LXI', 'Maruti Dzire VXI', 'Maruti Dzire ZXI', 'Maruti Eeco', 'Maruti Ertiga', 'Maruti Ignis', 'Maruti S-Presso', 'Maruti Swift', 'Maruti Swift Dzire', 'Maruti Vitara', 'Maruti Wagon R', 'Maruti XL6', 'Maserati Ghibli', 'Maserati Quattroporte', 'Mercedes-AMG C', 'Mercedes-Benz C-Class', 'Mercedes-Benz CLS', 'Mercedes-Benz E-Class', 'Mercedes-Benz GL-Class', 'Mercedes-Benz GLS', 'Mercedes-Benz S-Class', 'Mini Cooper', 'Nissan Kicks', 'Nissan X-Trail', 'Porsche Cayenne', 'Porsche Macan', 'Porsche Panamera', 'Renault Duster', 'Renault KWID', 'Renault Triber', 'Rolls-Royce Ghost', 'Skoda Octavia', 'Skoda Rapid', 'Skoda Superb', 'Tata Altroz', 'Tata Harrier', 'Tata Hexa', 'Tata Nexon', 'Tata Safari', 'Tata Tiago', 'Tata Tigor', 'Toyota Camry', 'Toyota Fortuner', 'Toyota Glanza', 'Toyota Innova', 'Toyota Yaris', 'Volkswagen Polo', 'Volkswagen Vento', 'Volvo S90', 'Volvo XC', 'Volvo XC60', 'Volvo XC90']

 brand in 80 unique values):
[' Audi', ' Audi ', ' BMW', ' BMW ', ' Datsun', ' Datsun ', ' Ferrari ', ' Ford', ' Ford ', ' Honda', ' Honda ', ' Hyundai', ' Hyundai ', ' ISUZU ', ' Land Rover', ' MG ', ' Mahindra', ' Mahindra ', ' Maruti', ' Maruti ', ' Mercedes-AMG ', ' Mercedes-Benz ', ' Mini ', ' Nissan ', ' Porsche', ' Renault', ' Renault ', ' Skoda', ' Skoda ', ' Tata', ' Tata ', ' Toyota', ' Toyota ', ' Volkswagen', ' Volkswagen ', 'Audi', 'Audi ', 'BMW', 'BMW ', 'Bentley', 'Datsun', 'Datsun ', 'Force', 'Ford', 'Ford ', 'Honda', 'Honda ', 'Hyundai', 'Hyundai ', 'ISUZU', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lexus', 'MG', 'Mahindra', 'Mahindra ', 'Maruti', 'Maruti ', 'Maserati', 'Mercedes-Benz', 'Mercedes-Benz ', 'Mini', 'Nissan', 'Porsche', 'Renault', 'Renault ', 'Rolls-Royce', 'Skoda', 'Skoda ', 'Tata', 'Tata ', 'Toyota', 'Toyota ', 'Volkswagen', 'Volkswagen ', 'Volvo', 'Volvo ']

 seller_type in 9 unique values):
['DEALER', 'Dealer', 'Delaer', 'Individual', 'Individuall', 'Individul', 'Trustmark Dealer', 'dealer', 'individual']

 fuel_type in 14 unique values):
[' Diesel', ' Petrol', 'CNG', 'DIESEL', 'Diesel', 'Electric', 'LPG', 'PETROL', 'Petrol', 'Petrol ', 'diesel', 'diesel ', 'petrol', 'petrol ']

 transmission_type in 2 unique values):
['Automatic', 'Manual']

In [9]:
df=df.drop(columns=['Unnamed: 0'])
df.head(30)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
5,Hyundai i10,Hyundai,i10,12,73000,Dealer,Petrol,Manual,20.36,1197.0,78.90,5.0,190000.0
6,Hyundai i20,Hyundai,i20,12,88000,Dealer,Petrol,Manual,18.5,NaN,80.00,5.0,275000.0
7,Maruti Wagon R,Maruti,Wagon R,7,50000,Individual,Petrol,Manual,20.51,NaN,67.04,5.0,351000.0
8,Ford Freestyle,Ford,Freestyle,2,30000,individual,Diesel,Manual,24.4,1498.0,98.63,5.0,775000.0
9,Maruti Swift Dzire,Maruti,Swift Dzire,10,75220,Dealer,Diesel,Manual,19.3,1248.0,73.90,5.0,390000.0
10,Maruti Swift,Maruti,Swift,6,34000,Dealer,Petrol,Manual,16.1,1197.0,85.00,5.0,450000.0
11,Hyundai Grand,Hyundai,Grand,1,15000,Individual,Petrol,Manual,NaN,1197.0,81.86,5.0,511000.0
12,Jeep Compass,Jeep,Compass,4,43726,Dealer,Diesel,Manual,17.1,1956.0,173.00,5.0,1625000.0
13,Hyundai Grand,Hyundai,Grand,5,13000,Dealer,Petrol,Manual,18.9,1197.0,82.00,5.0,455000.0
14,Maruti Swift,Maruti,Swift,5,47350,Individual,Diesel,Manual,25.2,NaN,74.00,5.0,640000.0
15,Mahindra Scorpio,Mahindra,Scorpio,10,15000,Individual,Diesel,Manual,15.4,2179.0,120.00,8.0,700000.0
16,Maruti Swift Dzire,Maruti,Swift Dzire,10,86000,Individual,Diesel,Manual,19.3,1248.0,73.90,5.0,420000.0
17,Maruti Wagon R,Maruti,Wagon R,3,10983,Dealer,Petrol,Manual,21.5,1197.0,81.80,5.0,425000.0
18,Ford Figo,Ford,Figo,8,44000,Dealer,Diesel,Manual,20.0,1399.0,68.10,5.0,235000.0
19,Honda City,Honda,City,11,93000,Individual,Petrol,Manual,17.0,1497.0,118.00,5.0,276000.0
20,Maruti Swift,Maruti,Swift,5,130130,Dealer,Diesel,Manual,25.2,1248.0,74.00,5.0,400000.0
21,Maruti Swift,Maruti,Swift,6,48000,Dealer,Petrol,Manual,16.1,1298.0,88.20,5.0,480000.0
22,Maruti Ertiga,Maruti,Ertiga,7,54000,Dealer,CNG,Manual,NaN,NaN,80.90,7.0,675000.0
23,Maruti Ciaz,Maruti,Ciaz,3,70000,Individual,Diesel,Manual,28.09,1248.0,88.50,5.0,725000.0
24,Hyundai i20,Hyundai,i20,12,50000,Individual,Petrol,Manual,17.0,NaN,80.00,5.0,300000.0
25,Hyundai Verna,Hyundai,Verna,3,3700,Dealer,Diesel,Manual,23.9,1582.0,126.20,5.0,1220000.0
26,Hyundai i20,Hyundai,i20,7,100000,Individual,Diesel,Manual,22.54,1396.0,88.73,5.0,550000.0
27,Maruti Vitara,Maruti,Vitara,1,16000,Dealer,Diesel,Automatic,24.3,1248.0,88.50,5.0,1125000.0
28,Honda Civic,Honda,Civic,12,23000,Dealer,Petrol,Manual,14.8,NaN,130.20,5.0,295000.0
29,Hyundai i20,Hyundai,i20,3,25000,Dealer,Petrol,Manual,18.6,1197.0,81.83,5.0,599000.0

In [10]:
print(f"\n Before cleaning {df['brand'].nunique()}")

df['brand']=df['brand'].str.strip()

print(f"\n after cleaning {df['brand'].nunique()}")
print(df['brand'].value_counts())

 Before cleaning 80

 after cleaning 32
brand
Maruti           5077
Hyundai          3025
Honda            1508
Mahindra         1031
Toyota            806
Ford              802
Volkswagen        634
Renault           550
BMW               443
Tata              435
Mercedes-Benz     339
Skoda             338
Audi              196
Datsun            172
Jaguar             61
Land Rover         51
Jeep               42
Kia                33
Porsche            22
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
ISUZU               2
Maserati            2
Ferrari             1
Mercedes-AMG        1
Force               1
Rolls-Royce         1
Name: count, dtype: int64

In [11]:
df['fuel_type'].unique()

array(['Diesel', 'CNG', 'Petrol', 'Petrol ', 'DIESEL', ' Petrol',
       'petrol ', 'PETROL', ' Diesel', 'diesel ', 'LPG', 'petrol',
       'diesel', 'Electric'], dtype=object)

In [12]:
df['fuel_type']=df['fuel_type'].str.strip().str.title()
df['fuel_type'].unique()

array(['Diesel', 'Cng', 'Petrol', 'Lpg', 'Electric'], dtype=object)

In [13]:
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,Cng,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [14]:
df['seller_type'].unique()

array(['Dealer', 'dealer', 'Individual', 'individual', 'DEALER',
       'Trustmark Dealer', 'Individul', 'Individuall', 'Delaer'],
      dtype=object)

In [15]:
df['seller_type']=df['seller_type'].str.strip().str.title()
df['seller_type'].unique()

array(['Dealer', 'Individual', 'Trustmark Dealer', 'Individul',
       'Individuall', 'Delaer'], dtype=object)

In [16]:
type_mapo={'Individul':'Individual',
           'Individuall':'Individual',
           'Delaer':'Dealer'
           }

df['seller_type']=df['seller_type'].replace(type_mapo)
df['seller_type'].unique()

array(['Dealer', 'Individual', 'Trustmark Dealer'], dtype=object)

In [17]:
df['seller_type'].value_counts()

seller_type
Dealer              9694
Individual          5792
Trustmark Dealer     175
Name: count, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15661 non-null  object
 1   brand              15661 non-null  object
 2   model              15661 non-null  object
 3   vehicle_age        15661 non-null  int64
 4   km_driven          15661 non-null  object
 5   seller_type        15661 non-null  object
 6   fuel_type          15661 non-null  object
 7   transmission_type  15661 non-null  object
 8   mileage            14376 non-null  object
 9   engine             13792 non-null  float64
 10  max_power          14862 non-null  float64
 11  seats              15218 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 1.6+ MB

In [19]:
df['km_driven']=df['km_driven'].astype(str).str.replace('kms','')
df['km_driven']=df['km_driven'].astype(str).str.replace('km','')
df['km_driven']=df['km_driven'].astype(str).str.replace(',','')

In [20]:
df['km_driven'].head(100)

0     67647
1     52000
2     48959
3     82000
4     34000
      ...
95    68000
96    98000
97    53892
98    20001
99    40000
Name: km_driven, Length: 100, dtype: object

In [21]:
df['km_driven']=df['km_driven'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15661 non-null  object
 1   brand              15661 non-null  object
 2   model              15661 non-null  object
 3   vehicle_age        15661 non-null  int64
 4   km_driven          15661 non-null  int64
 5   seller_type        15661 non-null  object
 6   fuel_type          15661 non-null  object
 7   transmission_type  15661 non-null  object
 8   mileage            14376 non-null  object
 9   engine             13792 non-null  float64
 10  max_power          14862 non-null  float64
 11  seats              15218 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 1.6+ MB

In [23]:
df.isnull().sum() *100/df.shape[0]

car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

In [26]:
before=len(df)
df=df.dropna(subset=['selling_price'])
after=len(df)
print(f"Dropped {before-after} where selling price is  missing ")

Dropped 158 where selling price is  missing

In [27]:
df.isnull().sum() *100/df.shape[0]

car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.185512
engine               11.946075
max_power             5.102238
seats                 2.825260
selling_price         0.000000
dtype: float64

In [29]:
engine_missing=df[df['engine'].isna()]['vehicle_age']
engine_present=df[df['engine'].notna()]['vehicle_age']

print(f"Average Vehicle where engine is: {engine_missing.mean():1f} years")
print(f"Average Vehicle where engine is:{engine_present.mean():1f}years")

Average Vehicle where engine is: 8.089093 years
Average Vehicle where engine is:5.758919years

In [30]:
df.isnull().sum() *100/df.shape[0]

car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.185512
engine               11.946075
max_power             5.102238
seats                 2.825260
selling_price         0.000000
dtype: float64

In [31]:
print("Engine distribution:")
print(f"  Mean:   {df['engine'].mean():.0f} cc")
print(f"  Median: {df['engine'].median():.0f} cc")

Engine distribution:
  Mean:   1480 cc
  Median: 1248 cc

In [34]:
for cat in ['engine','mileage','max_power']:
  median_value=df[cat].median()
  df[cat]=df[cat].fillna(median_value)
  print(f" filled {cat} with median values")

 filled engine with median values
 filled mileage with median values
 filled max_power with median values

/tmp/ipykernel_7510/1309967129.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cat]=df[cat].fillna(median_value)

In [33]:
df['mileage']=df['mileage'].astype(str).str.replace('kmpl','').str.replace('kmp','').str.strip()

df['mileage']=pd.to_numeric(df['mileage'],errors='coerce')
df['mileage'].head(100)

/tmp/ipykernel_7510/3268658611.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mileage']=df['mileage'].astype(str).str.replace('kmpl','').str.replace('kmp','').str.strip()
/tmp/ipykernel_7510/3268658611.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mileage']=pd.to_numeric(df['mileage'],errors='coerce')

0     19.87
1     33.54
2       NaN
3     15.40
4     16.00
      ...
95    13.00
96    22.10
97    24.30
98    13.50
99    17.80
Name: mileage, Length: 100, dtype: float64

In [35]:
df.isnull().sum()*100/df.shape[0]

car_name             0.00000
brand                0.00000
model                0.00000
vehicle_age          0.00000
km_driven            0.00000
seller_type          0.00000
fuel_type            0.00000
transmission_type    0.00000
mileage              0.00000
engine               0.00000
max_power            0.00000
seats                2.82526
selling_price        0.00000
dtype: float64

In [37]:
seat_mode=df['seats'].mode()[0]
df['seats']=df['seats'].fillna(seat_mode)
df['seats']

/tmp/ipykernel_7510/3513508255.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['seats']=df['seats'].fillna(seat_mode)

0        5.0
1        5.0
2        5.0
3        8.0
4        7.0
        ...
15656    7.0
15657    5.0
15658    5.0
15659    5.0
15660    5.0
Name: seats, Length: 15503, dtype: float64

In [38]:
df.isnull().sum()*100/df.shape[0]

car_name             0.0
brand                0.0
model                0.0
vehicle_age          0.0
km_driven            0.0
seller_type          0.0
fuel_type            0.0
transmission_type    0.0
mileage              0.0
engine               0.0
max_power            0.0
seats                0.0
selling_price        0.0
dtype: float64

In [39]:
df.duplicated().sum()

np.int64(301)

In [41]:
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [42]:
df.shape

(15202, 13)

In [43]:

import pandas as pd
from sklearn.metrics import mean_absolute_error

# Assume df is your cleaned dataset with a 'selling_price' column
# Step 1: Compute the mean selling price
mean_price = df['selling_price'].mean()

# Step 2: Build baseline predictions (same value for all records)
baseline_predictions = [mean_price] * len(df)

# Step 3: Calculate MAE
baseline_mae = mean_absolute_error(df['selling_price'], baseline_predictions)

print("Baseline MAE:", baseline_mae)

Baseline MAE: 871008.089693812